package model.exceptions;

public class DomainException extends RuntimeException {

	private static final long serialVersionUID = 1L;
	//AQUI É Q É A CLASSE EXCEPTION ELA É SERIALIZABLE, LOGO A DOMAIN
	//TAMBEM É SERIALIZABEL, É CONTEUDO MAIS A FRENTE DO JAVA
	// SÓ É PRECISO DECLARAR UMA VERSÃO PARA ESSA CLASSE DAMOS A 1L
	
	public DomainException(String msg) {
		super(msg);
	}
	//CONSTRUTOR QUE RECEBE UM STRING, Q PASSAMOS PARA O CONSTRUTOR DA SUPER CLASSE
	// É PRA PERMITIR QUE POSSAMOS INSTANCIAR A MINHA SESSÃO PERSONALIZADA PASSANDO UMA
	//MENSAGEM PRA ELA Q VAI SER ARMAZENADA DENTRO DA SUA EXCEÇÃO
	

	
	
	
}
